json.id product.id
json.name product.name
json.description product.description
json.price product.price
json.tax product.total
json.image_url product.image_url
json.discounted product.is_discounted?
json.instock product.instock
json.supplier_id product.supplier_id